name: bayes_yplus
channels:
  - conda-forge
  - defaults
dependencies:
  - versioneer
  - numpy
  - pymc>=5
  - pytensor
  - nutpie
  - numba
  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - jax==0.4.28
  - blackjax
  - numpyro
  - pip
  - pip:
    - "git+https://github.com/tvwenger/bayes_spec.git@main"
