[build-system]
requires = ["setuptools", "versioneer[toml]==0.29"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "bayes_yplus/_version.py"
versionfile_build = "bayes_yplus/_version.py"
tag_prefix = "v"
